# This file is used to make http requests (instead of using postman). 
# It uses REST Client vscode
//////////////////

@id = 0f686481-64e6-46c8-9123-4f650194c14g


GET http://localhost:3000/api/media/{{id}} HTTP/1.1

###
POST http://localhost:3000/api/example HTTP/1.1
content-type: application/json
{   
    "dummy_content": "dummy_content"
}

