apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{{M3_COMPONENT}}}-deployment"
  namespace: {{{M3_NAMESPACE}}}
  labels:
    app: "{{{M3_COMPONENT}}}-deployment"
spec:
  replicas: {{{M3_REPLICAS}}}
  selector:
    matchLabels:
      app: {{{M3_COMPONENT}}}
  template:
    metadata:
      labels:
        app: {{{M3_COMPONENT}}}
    spec:
      containers:
        - name: "{{{M3_COMPONENT}}}-main-container"
          image: "{{{M3_IMAGE}}}:{{{M3_VERSION}}}"
          env:
            - name: DB_URL
              value: {{{M3_ELEPHANTSQL_URL}}}
            - name: NODE_ENV
              value: {{{M3_NODE_ENV}}}
            - name: RABBITMQ_URL
              value: {{{M3_RABBITMQ_URL}}}
