apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-{{{M3_ENVIRONMENT}}}"
  namespace: "{{{M3_NAMESPACE}}}"
  labels:
    application: "{{{M3_PROJECT}}}"
    component: "{{{M3_COMPONENT}}}"
    environment: "{{{M3_ENVIRONMENT}}}"  
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
    - host: '{{{M3_HOST}}}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-{{{M3_ENVIRONMENT}}}"
                port:
                  number: {{{M3_PORT_BACKEND}}}
