apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-{{{M3_ENVIRONMENT}}}"
  namespace: "{{{M3_NAMESPACE}}}"
  labels:
    application: "{{{M3_PROJECT}}}"
    component: "{{{M3_COMPONENT}}}"
    environment: "{{{M3_ENVIRONMENT}}}"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-nfs
  resources:
    requests:
      storage: {{{M3_MEDIA_STORAGE_CAPACITY}}}