apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pickify-media
  namespace: {{{M3_NAMESPACE}}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-nfs
  resources:
    requests:
      storage: {{{M3_MEDIA_STORAGE_CAPACITY}}}